# Generated by Django 5.2.8 on 2025-12-02 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'فایل صوتی', 'verbose_name_plural': 'فایل\u200cهای صوتی'},
        ),
        migrations.AddField(
            model_name='audiofile',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='پیام خطا'),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='audio_file',
            field=models.FileField(upload_to='uploads/audio/', verbose_name='فایل صوتی'),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='status',
            field=models.CharField(choices=[('pending', 'در صف پردازش'), ('processing', 'در حال پردازش'), ('completed', 'تکمیل شده'), ('failed', 'خطا')], default='pending', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='transcript_text',
            field=models.TextField(blank=True, null=True, verbose_name='متن استخراج شده'),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
