# Generated by Django 5.2.8 on 2025-12-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_audiofile_options_audiofile_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='status',
            field=models.CharField(choices=[('uploading', 'در حال آپلود'), ('pending', 'در صف پردازش'), ('processing', 'در حال پردازش'), ('completed', 'تکمیل شده'), ('failed', 'خطا')], default='uploading', max_length=20, verbose_name='وضعیت'),
        ),
    ]
