# Generated by Django 5.2.8 on 2025-12-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_audiofile_task_id_alter_audiofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='model_name',
            field=models.CharField(choices=[('eboo', 'Eboo'), ('vira', 'Vira'), ('scribe', 'Scribe')], default='eboo', max_length=20, verbose_name='مدل پردازش'),
        ),
    ]
