# Generated by Django 5.2.8 on 2025-12-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_audiofile_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='is_video',
            field=models.BooleanField(default=False, verbose_name='فایل ویدیویی است؟'),
        ),
    ]
