# Generated by Django 5.2.8 on 2025-12-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_audiofile_is_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='source_url',
            field=models.URLField(blank=True, null=True, verbose_name='لینک منبع'),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/audio/', verbose_name='فایل صوتی'),
        ),
    ]
