# Generated by Django 5.2.8 on 2026-01-02 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_audiofile_source_url_alter_audiofile_audio_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'فایل پردازشی', 'verbose_name_plural': 'فایل\u200cهای پردازشی'},
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='source_url',
            field=models.URLField(blank=True, null=True, verbose_name='لینک فایل'),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(verbose_name='لینک منبع')),
                ('status', models.CharField(choices=[('created', 'ایجاد شده'), ('discovering', 'در حال بررسی لینک'), ('ready', 'آماده انتخاب'), ('failed', 'خطا')], default='created', max_length=20, verbose_name='وضعیت')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='پیام خطا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.AddField(
            model_name='audiofile',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.importbatch', verbose_name='ورودی لینک'),
        ),
    ]
