# Generated by Django 5.2.8 on 2026-01-02 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_audiofile_options_alter_audiofile_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان')),
                ('source_url', models.URLField(verbose_name='لینک فایل')),
                ('is_video', models.BooleanField(default=False, verbose_name='ویدیویی است؟')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='مدت (ثانیه)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.importbatch', verbose_name='دسته ایمپورت')),
            ],
        ),
    ]
