# Generated by Django 5.2.8 on 2026-01-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_importitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importbatch',
            name='source_url',
            field=models.TextField(verbose_name='لینک منبع'),
        ),
        migrations.AlterField(
            model_name='importitem',
            name='source_url',
            field=models.TextField(verbose_name='لینک فایل'),
        ),
    ]
